\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdftitle={homework3},
            pdfauthor={xw2598},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\newcommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}

  \title{homework3}
    \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
    \author{xw2598}
    \preauthor{\centering\large\emph}
  \postauthor{\par}
    \date{}
    \predate{}\postdate{}
  

\begin{document}
\maketitle

\section{problem2---write on the paper,this is a
bonus}\label{problem2write-on-the-paperthis-is-a-bonus}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(tidyverse)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## -- Attaching packages ---------------------------------------------------------- tidyverse 1.2.1 --
\end{verbatim}

\begin{verbatim}
## v ggplot2 3.0.0     v purrr   0.2.5
## v tibble  1.4.2     v dplyr   0.7.6
## v tidyr   0.8.1     v stringr 1.3.1
## v readr   1.1.1     v forcats 0.3.0
\end{verbatim}

\begin{verbatim}
## -- Conflicts ------------------------------------------------------------- tidyverse_conflicts() --
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{HeavySmoke =}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{"HeavySmoke.csv"}\NormalTok{,}\DataTypeTok{header =} \OtherTok{TRUE}\NormalTok{)}
\NormalTok{  HeavySmoke =}\StringTok{ }\NormalTok{HeavySmoke[, }\OperatorTok{-}\DecValTok{1}\NormalTok{] }
\CommentTok{#calculate the difference before and after 6 years quitting smoking}
\NormalTok{  HeavySmoke =}\StringTok{ }\KeywordTok{mutate}\NormalTok{(HeavySmoke,}\DataTypeTok{diff =}\NormalTok{ BMI_6yrs }\OperatorTok{-}\StringTok{ }\NormalTok{BMI_base)}
\CommentTok{#show the table }
\NormalTok{  HeavySmoke}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    BMI_base BMI_6yrs diff
## 1      25.6     31.1  5.5
## 2      24.4     27.6  3.2
## 3      31.0     36.6  5.6
## 4      20.4     20.8  0.4
## 5      22.3     23.2  0.9
## 6      22.2     23.8  1.6
## 7      20.8     26.1  5.3
## 8      23.5     31.0  7.5
## 9      26.6     29.2  2.6
## 10     23.0     24.0  1.0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#difference mean}
\NormalTok{  diff_mean =}\StringTok{ }\KeywordTok{mean}\NormalTok{(HeavySmoke}\OperatorTok{$}\NormalTok{diff)}
\CommentTok{#difference standard daviation}
\NormalTok{  diff_sd =}\StringTok{ }\KeywordTok{sd}\NormalTok{(HeavySmoke}\OperatorTok{$}\NormalTok{diff)}
\CommentTok{#Use one sample t-Test to test if the changes is equal to 0}
  \CommentTok{#Normality assumed}
  \CommentTok{#H0:mean difference = 0; H1: mean difference != 0}
  \CommentTok{#diff_mean = 3,36, diff_sd = 2.46, N = 10}
\NormalTok{  t_stat =}\StringTok{ }\NormalTok{diff_mean}\OperatorTok{/}\NormalTok{(diff_sd}\OperatorTok{/}\KeywordTok{sqrt}\NormalTok{(}\DecValTok{10}\NormalTok{))}
  \CommentTok{#Compare the test statistics with the critical value, alpha=0.05}
  \KeywordTok{qt}\NormalTok{(}\FloatTok{0.975}\NormalTok{,}\DecValTok{9}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2.262157
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
  \CommentTok{#t_stat>qt(9,0.975),reject H0}
\NormalTok{  p_value =}\StringTok{ }\DecValTok{2}\OperatorTok{*}\NormalTok{(}\DecValTok{1}\OperatorTok{-}\KeywordTok{pt}\NormalTok{(t_stat,}\DecValTok{9}\NormalTok{))}
  \KeywordTok{tibble}\NormalTok{(}
    \DataTypeTok{d_bar =}\NormalTok{ diff_mean,}
    \DataTypeTok{sd =}\NormalTok{ diff_sd,}
    \DataTypeTok{t_stat =}\NormalTok{ t_stat,}
    \DataTypeTok{critical_value =} \KeywordTok{qt}\NormalTok{(}\FloatTok{0.975}\NormalTok{,}\DecValTok{9}\NormalTok{),}
    \DataTypeTok{alpha =} \FloatTok{0.05}\NormalTok{,}
    \DataTypeTok{pvalue =}\NormalTok{ p_value}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 1 x 6
##   d_bar    sd t_stat critical_value alpha  pvalue
##   <dbl> <dbl>  <dbl>          <dbl> <dbl>   <dbl>
## 1  3.36  2.46   4.31           2.26  0.05 0.00195
\end{verbatim}

Interpretation: Since t\_stat = 4.30 \textgreater{}t9,0.975 and p-value
\textless{} 10\^{}-3, we reject the null hypothesis and conclude that
there are sufficient evidence that women`s BMI has changed after 6 years
quitting smoking.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{NeverSmoke =}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{"NeverSmoke.csv"}\NormalTok{,}\DataTypeTok{header =} \OtherTok{TRUE}\NormalTok{) }
\NormalTok{NeverSmoke =}\StringTok{ }\NormalTok{NeverSmoke[,}\OperatorTok{-}\DecValTok{1}\NormalTok{]}
\NormalTok{NeverSmoke =}\StringTok{ }\KeywordTok{mutate}\NormalTok{(NeverSmoke, }\DataTypeTok{d2 =}\NormalTok{ BMI_6yrs }\OperatorTok{-}\StringTok{ }\NormalTok{BMI_base)}
\NormalTok{BmiChange =}\StringTok{ }\KeywordTok{tibble}\NormalTok{(}\DataTypeTok{d1 =}\NormalTok{ HeavySmoke}\OperatorTok{$}\NormalTok{diff, }\DataTypeTok{d2 =}\NormalTok{ NeverSmoke}\OperatorTok{$}\NormalTok{d2)}
\CommentTok{#two sample}
\NormalTok{BmiChange}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 10 x 2
##       d1     d2
##    <dbl>  <dbl>
##  1 5.5    2.8  
##  2 3.2   -0.900
##  3 5.6   -2.1  
##  4 0.4    3.9  
##  5 0.900  1.70 
##  6 1.6    4.8  
##  7 5.3    3.5  
##  8 7.5    1.8  
##  9 2.60  -0.8  
## 10 1      0.8
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#using two sample t-test to test whether the difference of two samples` changes is equal to 0 }
  \CommentTok{#Normality assumed}
  \CommentTok{#H0: variances are equal; H1: variances are not equal  }
\NormalTok{d1_mean =}\StringTok{ }\KeywordTok{mean}\NormalTok{(BmiChange}\OperatorTok{$}\NormalTok{d1)}
\NormalTok{d1_sd =}\StringTok{ }\KeywordTok{sd}\NormalTok{(BmiChange}\OperatorTok{$}\NormalTok{d1)}
\NormalTok{d2_mean =}\StringTok{ }\KeywordTok{mean}\NormalTok{(BmiChange}\OperatorTok{$}\NormalTok{d2)}
\NormalTok{d2_sd =}\StringTok{ }\KeywordTok{sd}\NormalTok{(BmiChange}\OperatorTok{$}\NormalTok{d2)}
\CommentTok{#heavy smoke: n1 = 10, d1_bar = 3.36, sd1 = 2.46}
\CommentTok{#never smoke: n2 = 10, d2_bar = 1.55, sd2 = 2.28}
\NormalTok{F_stat =}\StringTok{ }\NormalTok{d1_sd}\OperatorTok{^}\DecValTok{2}\OperatorTok{/}\NormalTok{d2_sd}\OperatorTok{^}\DecValTok{2}
\KeywordTok{qf}\NormalTok{(}\FloatTok{0.975}\NormalTok{,}\DecValTok{9}\NormalTok{,}\DecValTok{9}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 4.025994
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#F_stat = 1.55 < qf(0.975,9,9)}
\CommentTok{#There not enough evidences to declare a different variance, fail to reject H0}
\NormalTok{s =}\StringTok{ }\KeywordTok{sqrt}\NormalTok{((}\DecValTok{9}\OperatorTok{*}\NormalTok{d1_sd}\OperatorTok{^}\DecValTok{2}\OperatorTok{+}\DecValTok{9}\OperatorTok{*}\NormalTok{d2_sd}\OperatorTok{^}\DecValTok{2}\NormalTok{)}\OperatorTok{/}\NormalTok{(}\DecValTok{10}\OperatorTok{+}\DecValTok{10}\OperatorTok{-}\DecValTok{2}\NormalTok{))}
 \CommentTok{#H0:d1_bar = d2_bar; H1:d1_bar != d2_bar}
\NormalTok{t2_stat =}\StringTok{ }\NormalTok{(d1_mean}\OperatorTok{-}\NormalTok{d2_mean)}\OperatorTok{/}\NormalTok{(s}\OperatorTok{*}\KeywordTok{sqrt}\NormalTok{(}\DecValTok{1}\OperatorTok{/}\DecValTok{10}\OperatorTok{+}\DecValTok{1}\OperatorTok{/}\DecValTok{10}\NormalTok{))}
\KeywordTok{qt}\NormalTok{(}\FloatTok{0.975}\NormalTok{,}\DecValTok{18}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2.100922
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#t2_stat<t18,0.975,fail to reject H0 and declare there is no enough evidencethe two sample has different mean.}
\KeywordTok{tibble}\NormalTok{(}
  \DataTypeTok{d1_bar =}\NormalTok{ d1_mean,}
  \DataTypeTok{sd1 =}\NormalTok{d1_sd,}
  \DataTypeTok{d2_bar =}\NormalTok{ d2_mean,}
  \DataTypeTok{sd2 =}\NormalTok{ d2_sd,}
  \DataTypeTok{estimate_s =}\NormalTok{ s,}
  \DataTypeTok{F_stat =}\NormalTok{ F_stat,}
  \DataTypeTok{F_Critical =} \KeywordTok{qf}\NormalTok{(}\FloatTok{0.975}\NormalTok{,}\DecValTok{9}\NormalTok{,}\DecValTok{9}\NormalTok{),}
  \DataTypeTok{t_stat =}\NormalTok{ t2_stat,}
  \DataTypeTok{t_Critical =} \KeywordTok{qt}\NormalTok{(}\FloatTok{0.975}\NormalTok{,}\DecValTok{18}\NormalTok{)}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 1 x 9
##   d1_bar   sd1 d2_bar   sd2 estimate_s F_stat F_Critical t_stat t_Critical
##    <dbl> <dbl>  <dbl> <dbl>      <dbl>  <dbl>      <dbl>  <dbl>      <dbl>
## 1   3.36  2.46   1.55  2.28       2.37   1.16       4.03   1.70       2.10
\end{verbatim}

Interpretation: On the significance level of 0.05, we fail to reject the
H0 and conclude that there is no enough evidence that BMI changes are
different between the two groups--women who quitted smoking and women
who never smoked over the 6 years.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Construct a 95% CI for part2}
\NormalTok{CI =}\StringTok{ }\KeywordTok{c}\NormalTok{((d1_mean }\OperatorTok{-}\StringTok{ }\NormalTok{d2_mean) }\OperatorTok{-}\StringTok{ }\KeywordTok{qt}\NormalTok{(}\FloatTok{0.975}\NormalTok{,}\DecValTok{18}\NormalTok{)}\OperatorTok{*}\NormalTok{s}\OperatorTok{*}\KeywordTok{sqrt}\NormalTok{(}\DecValTok{1}\OperatorTok{/}\DecValTok{10}\OperatorTok{+}\DecValTok{1}\OperatorTok{/}\DecValTok{10}\NormalTok{), (d1_mean }\OperatorTok{-}\StringTok{ }\NormalTok{d2_mean) }\OperatorTok{+}\StringTok{ }\KeywordTok{qt}\NormalTok{(}\FloatTok{0.975}\NormalTok{,}\DecValTok{18}\NormalTok{)}\OperatorTok{*}\NormalTok{s}\OperatorTok{*}\KeywordTok{sqrt}\NormalTok{(}\DecValTok{1}\OperatorTok{/}\DecValTok{10}\OperatorTok{+}\DecValTok{1}\OperatorTok{/}\DecValTok{10}\NormalTok{)) }
\NormalTok{CI}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] -0.4214324  4.0414324
\end{verbatim}

Interpretation: We are 95\% confident that the true mean difference of
Bmi over 6 years changes between women who quitted smoking and who never
smoked would be in (-0.421, 4.041)

Question a: I would design the study as a prespective cohort study since
we have specific exposures and source population. In cohort study we
needn`t to care much about randomizaton but we do need to care about
subjects choosing. The location of choosing place may cause bias, for
example, if we choose subjects from the hospital, the results may seem
not true. Also, age, health condition, habits of exercises,nutrition
differences can also cause bias. So we should make sure all of the
factors that may cause BMI change among the two group subjects are the
same. Question b was written on the paper(attached in pdf)

\section{problem3}\label{problem3}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{knee =}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{"Knee.csv"}\NormalTok{,}\DataTypeTok{header =} \OtherTok{TRUE}\NormalTok{)}
\NormalTok{descrip =}\StringTok{ }\KeywordTok{tibble}\NormalTok{(}
  \DataTypeTok{var =} \KeywordTok{c}\NormalTok{(}\StringTok{"Below"}\NormalTok{, }\StringTok{"Average"}\NormalTok{, }\StringTok{"Above"}\NormalTok{ ),}
  \DataTypeTok{n =} \KeywordTok{c}\NormalTok{(}\DecValTok{8}\NormalTok{,}\DecValTok{10}\NormalTok{,}\DecValTok{7}\NormalTok{),}
  \DataTypeTok{mean =} \KeywordTok{c}\NormalTok{(}\KeywordTok{mean}\NormalTok{(knee}\OperatorTok{$}\NormalTok{Below,}\DataTypeTok{na.rm =} \OtherTok{TRUE}\NormalTok{),}\KeywordTok{mean}\NormalTok{(knee}\OperatorTok{$}\NormalTok{Average,}\DataTypeTok{na.rm =} \OtherTok{TRUE}\NormalTok{),}\KeywordTok{mean}\NormalTok{(knee}\OperatorTok{$}\NormalTok{Above,}\DataTypeTok{na.rm =} \OtherTok{TRUE}\NormalTok{)),}
  \DataTypeTok{sd =}  \KeywordTok{c}\NormalTok{(}\KeywordTok{sd}\NormalTok{(knee}\OperatorTok{$}\NormalTok{Below,}\DataTypeTok{na.rm =} \OtherTok{TRUE}\NormalTok{), }\KeywordTok{sd}\NormalTok{(knee}\OperatorTok{$}\NormalTok{Average,}\DataTypeTok{na.rm =} \OtherTok{TRUE}\NormalTok{),}\KeywordTok{sd}\NormalTok{(knee}\OperatorTok{$}\NormalTok{Above,}\DataTypeTok{na.rm =} \OtherTok{TRUE}\NormalTok{))}
\NormalTok{  )}

\NormalTok{descrip}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 3 x 4
##   var         n  mean    sd
##   <chr>   <dbl> <dbl> <dbl>
## 1 Below       8  38    5.48
## 2 Average    10  33    3.92
## 3 Above       7  23.6  4.20
\end{verbatim}

Comments:The mean decreasing order is :above,averange, below. This means
people who have a worse physical status will need more time in physical
therapy to get a successful rehabilitation. The sd decreasing order is
:averange, above, below. The smaller sd value is , the more convencing
that the group`s mean can represent its charater.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ins1 =}\StringTok{ }\KeywordTok{na.omit}\NormalTok{(knee}\OperatorTok{$}\NormalTok{Below)}
\NormalTok{ins2 =}\StringTok{ }\KeywordTok{na.omit}\NormalTok{(knee}\OperatorTok{$}\NormalTok{Average)}
\NormalTok{ins3 =}\StringTok{ }\KeywordTok{na.omit}\NormalTok{(knee}\OperatorTok{$}\NormalTok{Above)}
\NormalTok{time =}\StringTok{ }\KeywordTok{c}\NormalTok{(ins1,ins2,ins3)}
\NormalTok{ind<-}\KeywordTok{c}\NormalTok{(}\KeywordTok{rep}\NormalTok{(}\DecValTok{1}\NormalTok{,}\KeywordTok{length}\NormalTok{(ins1)),}\KeywordTok{rep}\NormalTok{(}\DecValTok{2}\NormalTok{,}\KeywordTok{length}\NormalTok{(ins2)),}\KeywordTok{rep}\NormalTok{(}\DecValTok{3}\NormalTok{,}\KeywordTok{length}\NormalTok{(ins3)))}
\NormalTok{new_data<-}\KeywordTok{as.data.frame}\NormalTok{(}\KeywordTok{cbind}\NormalTok{(time,ind))}
\CommentTok{# Perform an ANOVA test:}
\CommentTok{#H0:respect means of "average","below","above" groups are the same}
\CommentTok{#H1:respect means of "average","below","above" groups are not the same}
\NormalTok{new_data}\OperatorTok{$}\NormalTok{ind =}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(new_data}\OperatorTok{$}\NormalTok{ind)}
\NormalTok{res1<-}\KeywordTok{aov}\NormalTok{(time}\OperatorTok{~}\NormalTok{ind, }\DataTypeTok{data=}\NormalTok{new_data)}
\KeywordTok{qf}\NormalTok{(}\FloatTok{0.99}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{22}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 5.719022
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(res1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##             Df Sum Sq Mean Sq F value   Pr(>F)    
## ind          2  795.2   397.6   19.28 1.45e-05 ***
## Residuals   22  453.7    20.6                     
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

Because F\_stat = 19.28 \textgreater{} F0.99,2,22 = 5.72 , p-value =
1.45e-05, fail to reject H0. At 0.01 significance level, we reject the
null hypothesis and conclude that at least two of mean days required in
physical therapy from three groups are different.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(multcomp)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#pairwise comparisons }
\CommentTok{#bonferroni}
\KeywordTok{pairwise.t.test}\NormalTok{(new_data}\OperatorTok{$}\NormalTok{time, new_data}\OperatorTok{$}\NormalTok{ind,}\DataTypeTok{p.adj=}\StringTok{'bonferroni'}\NormalTok{,}\DataTypeTok{conf.level =} \FloatTok{0.01}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  new_data$time and new_data$ind 
## 
##   1       2     
## 2 0.0898  -     
## 3 1.1e-05 0.0011
## 
## P value adjustment method: bonferroni
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Tukey}
\KeywordTok{TukeyHSD}\NormalTok{(res1,}\DataTypeTok{conf.level =} \FloatTok{0.01}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Tukey multiple comparisons of means
##     1% family-wise confidence level
## 
## Fit: aov(formula = time ~ ind, data = new_data)
## 
## $ind
##           diff        lwr        upr     p adj
## 2-1  -5.000000  -5.290913  -4.709087 0.0736833
## 3-1 -14.428571 -14.745984 -14.111159 0.0000102
## 3-2  -9.428571  -9.730808  -9.126334 0.0010053
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Dunnett}
\NormalTok{test.dunnett=}\KeywordTok{glht}\NormalTok{(res1, }\DataTypeTok{linfct=}\KeywordTok{mcp}\NormalTok{(}\DataTypeTok{ind =}\StringTok{"Dunnet"}\NormalTok{),}\DataTypeTok{conf.level =} \FloatTok{0.01}\NormalTok{) }
\KeywordTok{summary}\NormalTok{(test.dunnett)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##   Simultaneous Tests for General Linear Hypotheses
## 
## Multiple Comparisons of Means: Dunnett Contrasts
## 
## 
## Fit: aov(formula = time ~ ind, data = new_data)
## 
## Linear Hypotheses:
##            Estimate Std. Error t value Pr(>|t|)    
## 2 - 1 == 0   -5.000      2.154  -2.321   0.0543 .  
## 3 - 1 == 0  -14.429      2.350  -6.139 6.93e-06 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## (Adjusted p values reported -- single-step method)
\end{verbatim}

The bonferroni,Tukey and Dunnut results all indicate that there is a
statistically significant difference between the ``below'' and ``above''
and ``averange'' and ``above''. But Dunnet p-value is smaller than
Turkey`s p-value than bonferroni.

Q4.There are extremely strong evidence that people who are above or
average physical status will need obviously less time in physical
therapy until successful rehabillitation than people who are below
physical status. But whether there is difference between people who are
above and average physical status, we are only 94\% confident that above
physical status people will require less time than average people.

\section{problem4}\label{problem4}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(datasets)}
\NormalTok{ncba =}\StringTok{ }\KeywordTok{as.tibble}\NormalTok{(UCBAdmissions)}
\CommentTok{#overall proportion of men}
\NormalTok{p_male =}\StringTok{ }\KeywordTok{sum}\NormalTok{(}\KeywordTok{filter}\NormalTok{(ncba,Admit }\OperatorTok{==}\StringTok{ "Admitted"}\NormalTok{, Gender }\OperatorTok{==}\StringTok{ "Male"}\NormalTok{ )}\OperatorTok{$}\NormalTok{n)}\OperatorTok{/}\KeywordTok{sum}\NormalTok{((}\KeywordTok{filter}\NormalTok{(ncba,Gender }\OperatorTok{==}\StringTok{ "Male"}\NormalTok{ ))}\OperatorTok{$}\NormalTok{n)}
\CommentTok{#overall number of men}
\NormalTok{n_man =}\StringTok{ }\KeywordTok{sum}\NormalTok{(}\KeywordTok{filter}\NormalTok{(ncba,Gender }\OperatorTok{==}\StringTok{ "Male"}\NormalTok{ )}\OperatorTok{$}\NormalTok{n)}
\CommentTok{#overall proportion of women}
\NormalTok{p_female =}\StringTok{ }\KeywordTok{sum}\NormalTok{(}\KeywordTok{filter}\NormalTok{(ncba,Admit }\OperatorTok{==}\StringTok{ "Admitted"}\NormalTok{, Gender }\OperatorTok{==}\StringTok{ "Female"}\NormalTok{ )}\OperatorTok{$}\NormalTok{n)}\OperatorTok{/}\KeywordTok{sum}\NormalTok{((}\KeywordTok{filter}\NormalTok{(ncba,Gender }\OperatorTok{==}\StringTok{ "Female"}\NormalTok{ ))}\OperatorTok{$}\NormalTok{n)}
\CommentTok{#overall number of women}
\NormalTok{n_women =}\StringTok{ }\KeywordTok{sum}\NormalTok{(}\KeywordTok{filter}\NormalTok{(ncba,Gender }\OperatorTok{==}\StringTok{ "Female"}\NormalTok{ )}\OperatorTok{$}\NormalTok{n)}
\CommentTok{#approximation}
\NormalTok{n_women}\OperatorTok{*}\NormalTok{p_female}\OperatorTok{*}\NormalTok{(}\DecValTok{1}\OperatorTok{-}\NormalTok{p_female)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 387.927
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n_man}\OperatorTok{*}\NormalTok{p_male}\OperatorTok{*}\NormalTok{(}\DecValTok{1}\OperatorTok{-}\NormalTok{p_male)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 664.6652
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#np(1-p)>5}
\CommentTok{#Normal Approximation of Binominal}
\NormalTok{var_men =}\StringTok{ }\NormalTok{p_male}\OperatorTok{*}\NormalTok{(}\DecValTok{1}\OperatorTok{-}\NormalTok{p_male)}\OperatorTok{/}\NormalTok{n_man}
\NormalTok{var_women =}\StringTok{ }\NormalTok{p_female}\OperatorTok{*}\NormalTok{(}\DecValTok{1}\OperatorTok{-}\NormalTok{p_female)}\OperatorTok{/}\NormalTok{n_women}
\CommentTok{#95%CI }
\NormalTok{CI =}\StringTok{ }\KeywordTok{c}\NormalTok{((p_male }\OperatorTok{-}\StringTok{ }\NormalTok{p_female) }\OperatorTok{-}\StringTok{ }\KeywordTok{qnorm}\NormalTok{(}\FloatTok{0.975}\NormalTok{)}\OperatorTok{*}\KeywordTok{sqrt}\NormalTok{(var_men}\OperatorTok{+}\NormalTok{var_women), (p_male }\OperatorTok{-}\StringTok{ }\NormalTok{p_female) }\OperatorTok{+}\StringTok{ }\KeywordTok{qnorm}\NormalTok{(}\FloatTok{0.975}\NormalTok{)}\OperatorTok{*}\KeywordTok{sqrt}\NormalTok{(var_men}\OperatorTok{+}\NormalTok{var_women)) }
\NormalTok{CI}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.1134470 0.1698439
\end{verbatim}

Interpretation: We are 95\% confident that the true mean difference of
difference proportions of men vs women admitted at Berkeley would be in
(0.1134470,0.1698439)

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#H0:p1 = p2; H1: p1!=p2}
\NormalTok{z_test =}\StringTok{ }\ControlFlowTok{function}\NormalTok{(p1,p2,n1,n2)\{}
\NormalTok{  p =}\StringTok{ }\NormalTok{(n1}\OperatorTok{*}\NormalTok{p1}\OperatorTok{+}\NormalTok{n2}\OperatorTok{*}\NormalTok{p2)}\OperatorTok{/}\NormalTok{(n1}\OperatorTok{+}\NormalTok{n2);}
\NormalTok{  z_stat =}\StringTok{ }\NormalTok{(}\KeywordTok{abs}\NormalTok{(p1}\OperatorTok{-}\NormalTok{p2)}\OperatorTok{-}\NormalTok{(}\DecValTok{1}\OperatorTok{/}\NormalTok{(}\DecValTok{2}\OperatorTok{*}\NormalTok{n1) }\OperatorTok{+}\StringTok{ }\DecValTok{1}\OperatorTok{/}\NormalTok{(}\DecValTok{2}\OperatorTok{*}\NormalTok{n2)))}\OperatorTok{/}\KeywordTok{sqrt}\NormalTok{(p}\OperatorTok{*}\NormalTok{(}\DecValTok{1}\OperatorTok{-}\NormalTok{p)}\OperatorTok{*}\NormalTok{(}\DecValTok{1}\OperatorTok{/}\NormalTok{n1 }\OperatorTok{+}\StringTok{ }\DecValTok{1}\OperatorTok{/}\NormalTok{n2));}
\NormalTok{  pvalue =}\StringTok{ }\DecValTok{2}\OperatorTok{*}\NormalTok{(}\DecValTok{1}\OperatorTok{-}\KeywordTok{qnorm}\NormalTok{(z_stat));}
  \KeywordTok{return}\NormalTok{(z_stat)}
\NormalTok{\}}
\NormalTok{ z_stat =}\StringTok{ }\KeywordTok{z_test}\NormalTok{(}\FloatTok{0.45}\NormalTok{,}\FloatTok{0.30}\NormalTok{,}\DecValTok{2691}\NormalTok{,}\DecValTok{1835}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in qnorm(z_stat): 产生了NaNs
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#pvalue}
\NormalTok{  pvalue =}\StringTok{ }\DecValTok{2}\OperatorTok{*}\NormalTok{(}\DecValTok{1}\OperatorTok{-}\KeywordTok{pnorm}\NormalTok{(z_stat))}
\NormalTok{  pvalue}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{qnorm}\NormalTok{(}\FloatTok{0.975}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.959964
\end{verbatim}

z\_stat \textgreater{} z0.975.At the 0.05 significance level,we reject
H0 and conclude that the proportion of women admitted at Berkeley is
different with the proportion of men admitted at Berkeley.


\end{document}
